version: '3.8'


services:

  ui_test_hosting:
    build: .
    image: "ui_test_hosting"
    volumes:
      - .:/ui_test_app
      - allure_results:/ui_test_app/allure-results


  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 3
      KEEP_HISTORY: 5
    ports:
      - "5050:5050"
    volumes:
      - allure_results:/app/allure-results
      - allure_report:/app/allure-report
      - allure_projects:/app/projects

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"


  chrome:
    image: "selenium/standalone-chrome:120.0"
    hostname: chrome
    privileged: true
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=3

volumes:
  allure_projects:
  allure_report:
  allure_results:
